# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fa040029412c55314e85f21669597da17097784f06a61ba96d35a3d9a5939c63c10e9bbe2f40b2d5facb1a3a0daf14bd276226012c05244e5ddd741a6570aa4
  redis_server: redis
  redis_port: 6379
  redis_cache_database: 0
  redis_cache_namespace: 'data_cycle_base'
  puma_max_workers: <%= ENV["PUMA_MAX_WORKERS"] %>
  puma_max_memory: <%= ENV["PUMA_MAX_MEMORY"] %>
  puma_max_threads: <%= ENV["PUMA_MAX_THREADS"] %>

test:
  secret_key_base: 211fc8bff1d3492ace234c1879eec5ac63cba420574f41ec3b8bcc38c50cfaa5bc8219a1ca011ddf7fea645ba2f09a5395386ffcc6e483eab232d64f941ba8b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  redis_server: <%= ENV["REDIS_SERVER"] %>
  redis_port: <%= ENV["REDIS_PORT"] %>
  redis_cache_database: <%= ENV["REDIS_CACHE_DATABASE"] %>
  redis_cache_namespace: <%= ENV["REDIS_CACHE_NAMESPACE"] %>
  puma_max_workers: <%= ENV["PUMA_MAX_WORKERS"] %>
  puma_max_memory: <%= ENV["PUMA_MAX_MEMORY"] %>
  puma_max_threads: <%= ENV["PUMA_MAX_THREADS"] %>

# optional for specific release environment
#release:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
